local gc = Var("GameCommand");
return Def.ActorFrame {
	Def.Quad{
		InitCommand=function(self)
			self:y(0):x(-74):zoomto(16,16):rotationz(45)
		end;
		GainFocusCommand=function(self)
			self:x(-94):diffuse(color("#f8c430"))
		end;
		LoseFocusCommand=function(self)
			self:x(-74):diffuse(color("#919191"))
		end;
	};
	Def.Quad{
		InitCommand=function(self)
			self:y(0):x(74):zoomto(16,16):rotationz(45)
		end;
		GainFocusCommand=function(self)
			self:x(54):diffuse(color("#cd7b0d"))
		end;
		LoseFocusCommand=function(self)
			self:x(74):diffuse(color("#919191"))
		end;
	};
	Def.Quad{
		InitCommand=function(self)
			self:y(6):x(-6):zoomto(160,12)
		end;
		GainFocusCommand=function(self)
			self:x(-26):diffuse(color("#cd7b0d"))
		end;
		LoseFocusCommand=function(self)
			self:x(-6):diffuse(color("#919191"))
		end;
	};
	Def.Quad{
		InitCommand=function(self)
			self:y(-6):x(6):zoomto(160,12)
		end;
		GainFocusCommand=function(self)
			self:x(-14):diffuse(color("#f8c430"))
		end;
		LoseFocusCommand=function(self)
			self:x(6):diffuse(color("#919191"))
		end;
	};
	LoadFont("Common Normal") .. {
		Text=string.upper(THEME:GetString("ScreenTitleMenu",gc:GetText()));
		InitCommand=function(self)
			self:strokecolor(color("#000000"))
		end;
		GainFocusCommand=function(self)
			self:x(-20)
		end;
		LoseFocusCommand=function(self)
			self:x(0)
		end;
	};
};